[package]
name = "mbrman"
version = "0.1.0"
authors = ["Cecile Tonglet <cecile.tonglet@cecton.com>"]
edition = "2018"
license = "MIT"
description = "MBR Partition Management in Rust"
repository = "https://github.com/cecton/mbrman"
homepage = "https://github.com/cecton/mbrman"
documentation = "https://docs.rs/mbrman"
readme = "README.md"
keywords = ["mbr", "partition", "table", "filesystem", "disk"]
categories = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[badges]
travis-ci = { repository = "cecton/mbrman" }
is-it-maintained-issue-resolution = { repository = "cecton/mbrman" }
is-it-maintained-open-issues = { repository = "cecton/mbrman" }

[dependencies]
bitvec = "0.15"
bincode = "1.0.1"
serde_derive = "1.0.83"
serde = "1.0.83"
derive-error = "0.0.4"
